#!/bin/bash
alias node="\$HOME/.config/nvm/10.12.0/bin/node"
alias npm="\$HOME/.config/nvm/10.12.0/bin/npm"
./node_modules/.bin/pkg src/2famsg.js --out-path=bin --targets=macos
codesign -s "3rd Party Mac Developer Application" bin/2famsg
